classdef TestGeneratorSourceEstimate < matlab.unittest.TestCase
    methods (Test)
        function estimatesLatticesAndMatrices(testCase)
            params = struct('lattice', struct('type', 'Cartesian', ...
                'counts', [2, 3, 4]));
            testCase.verifyEqual(estimate_generator_source_rows(params), 24);

            params.lattice = struct('type', 'Scan Parameter Matrix', ...
                'nSpeeds', 3, 'nPowers', 4, 'patchNx', 5, 'patchNy', 6);
            testCase.verifyEqual(estimate_generator_source_rows(params), 360);

            params.lattice = struct('type', 'Single Exposure Count Parameter Matrix', ...
                'nExposureCounts', 3, 'nPowers', 2, 'patchNx', 4, 'patchNy', 5);
            testCase.verifyEqual(estimate_generator_source_rows(params), 120);
        end

        function estimatesEnabledGratingSegments(testCase)
            starts = [1, 1, 0, nan; 1, 2, 0, 1; 2, 1, nan, 1];
            params = struct('lattice', struct( ...
                'type', 'Segmented Grating', ...
                'channelStartsUm', starts, ...
                'nDepths', 2, ...
                'nPeriods1', 3, ...
                'slabCopies1', 2, ...
                'nPeriods2', 5, ...
                'slabCopies2', 1));
            expectedPerDepth = 2 * 3 * 2 + 2 * 5;
            testCase.verifyEqual(estimate_generator_source_rows(params), ...
                2 * expectedPerDepth);
        end

        function releaseEstimateIsAConservativeUpperBound(testCase)
            params = struct('lattice', struct( ...
                'type', 'Hexagon Release Cut Array', ...
                'sideLengthUm', 100, ...
                'releaseHatchPitchUm', 10, ...
                'releaseRingCount', 2, ...
                'releaseLayerCount', 3, ...
                'releaseRepeatCount', 2, ...
                'arraySelectionMask', logical([1, 0; 1, 1])));
            perCellLayerUpperBound = 6 * 2 + 3 * (ceil(200 / 10) + 2);
            testCase.verifyEqual(estimate_generator_source_rows(params), ...
                perCellLayerUpperBound * 3 * 2 * 3);
        end

        function overflowAndUnknownTypesAreRejected(testCase)
            params = struct('lattice', struct('type', 'Cartesian', ...
                'counts', [flintmax, 2, 2]));
            testCase.verifyError(@() estimate_generator_source_rows(params), ...
                'estimateGeneratorRows:Overflow');

            params.lattice = struct('type', 'Unknown');
            testCase.verifyError(@() estimate_generator_source_rows(params), ...
                'estimateGeneratorRows:UnsupportedType');
        end
    end
end
