classdef TestPointDwellParameterMatrix < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addSupportPath(testCase)
            repoRoot = fileparts(fileparts(mfilename('fullpath')));
            supportFolder = fullfile(repoRoot, 'support_files');
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(supportFolder));
        end
    end

    methods (Test)
        function createsOneRegionPerDwellPowerPair(testCase)
            params = localParams();

            [data, ~, summary] = generate_point_cloud(params);

            testCase.verifySize(data, [12, 5]);
            testCase.verifyEqual(data(:, 4), [ ...
                10; 10; 20; 20; 30; 30; ...
                10; 10; 20; 20; 30; 30]);
            testCase.verifyEqual(data(:, 5), [ ...
                repmat(0.05, 6, 1); repmat(0.25, 6, 1)], ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(data(:, 3), repmat(-0.02, 12, 1), ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(summary.dwellRange, [0.05, 0.25], ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(summary.powerRange, [10, 30], ...
                'AbsTol', 1e-12);
        end

        function regionOriginsFollowPowerColumnsAndDwellRows(testCase)
            data = generate_point_cloud(localParams());
            firstPointOfEachRegion = data(1:2:end, 1:2);

            testCase.verifyEqual(firstPointOfEachRegion, [ ...
                1.0, 2.0; ...
                1.3, 2.0; ...
                1.6, 2.0; ...
                1.0, 2.4; ...
                1.3, 2.4; ...
                1.6, 2.4], 'AbsTol', 1e-12);
        end

        function rejectsNonpositiveDwellTime(testCase)
            params = localParams();
            params.lattice.dwellStartSeconds = 0;

            try
                generate_point_cloud(params);
                testCase.verifyFail('Expected a nonpositive dwell time to be rejected.');
            catch err
                testCase.verifyTrue(contains(err.message, 'Dwell start must be greater than 0'));
            end
        end
    end
end

function params = localParams()
params = struct();
params.lattice = struct( ...
    'type', "Point Dwell Parameter Matrix", ...
    'displayDistanceUnit', 'mm', ...
    'nDwells', 2, ...
    'dwellStartSeconds', 0.05, ...
    'dwellEndSeconds', 0.25, ...
    'nPowers', 3, ...
    'powerStart', 10, ...
    'powerEnd', 30, ...
    'patchNx', 2, ...
    'patchNy', 1, ...
    'patchPitchXUm', 100, ...
    'patchPitchYUm', 100, ...
    'gapXUm', 200, ...
    'gapYUm', 400, ...
    'originUm', [1000, 2000, -20]);
end
